### ISSUE TITLE
Unable to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by deadmantfa** [AFK-OS/una#22]
Trying to install it on Ubuntu 22.04 using the command mentioned in the README, no errors just doesnt do anything

![image](https://user-images.githubusercontent.com/1812611/169964138-2f5c8e7d-7d49-48bd-975d-bad410f85b5e.png)

screenshot of the output

**Comment by jonas-w** [comment]
Same for debian-bullseye

**Comment by Abdullah112006** [comment]
Do You found any solution?

**Comment by jonas-w** [comment]
Nope, i'm now using [tap](https://github.com/hwittenborn/tap)

**Comment by jonas-w** [comment]
Here some debug output for the developer:
```
+ gpg --dearmor
+ wget -qO - https://proget.makedeb.org/debian-feeds/makedeb.pub
+ sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg
+ echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org makedeb main'
+ sudo tee /etc/apt/sources.list.d/makedeb.list
+ sudo apt-get update
+ sudo apt-get install makedeb
+ git clone https://github.com/AFK-OS/una
Cloning into 'una'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 213 (delta 0), reused 1 (delta 0), pack-reused 207
Receiving objects: 100% (213/213), 52.48 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (112/112), done.
+ cd una
+ bash -x ./una update
++ tput bold
+ bold=''
++ tput sgr0
+ normal=''
+ red=''
+ green=''
+ yellow=''
+ blue=''
+ magenta=''
+ cyan=''
+ version=v3.2.0
+ set -e
+ echo 'una v3.2.0'
una v3.2.0
+ [[ 1000 == \0 ]]
+ LOCKFILE=/tmp/una.lock
+ [[ -e /tmp/una.lock ]]
+ trap 'rm -f /tmp/una.lock; tput cnorm; exit' INT TERM EXIT
+ echo 69509
+ [[ ! -d /var/lib/una ]]
+ echo
+ info 'creating una directory and config files'
+ echo -e '>> creating una directory and config files'
>> creating una directory and config files
+ mkdir -p /home/jonas/.config/autostart
+ cat
+ cat
+ sudo tee /etc/una/config
+ rm -f /tmp/una.lock
+ tput cnorm
+ exit
+ bash -x ./una install una-bin
++ tput bold
+ bold=''
++ tput sgr0
+ normal=''
+ red=''
+ green=''
+ yellow=''
+ blue=''
+ magenta=''
+ cyan=''
+ version=v3.2.0
+ set -e
+ echo 'una v3.2.0'
una v3.2.0
+ [[ 1000 == \0 ]]
+ LOCKFILE=/tmp/una.lock
+ [[ -e /tmp/una.lock ]]
+ trap 'rm -f /tmp/una.lock; tput cnorm; exit' INT TERM EXIT
+ echo 69520
+ [[ ! -d /var/lib/una ]]
+ echo
+ info 'creating una directory and config files'
+ echo -e '>> creating una directory and config files'
>> creating una directory and config files
+ mkdir -p /home/jonas/.config/autostart
+ cat
+ cat
+ sudo tee /etc/una/config
+ rm -f /tmp/una.lock
+ tput cnorm
+ exit
+ una help
./install.sh: line 16: una: command not found
```

**Comment by LI3GE** [comment]
Hey guys, I got a little obsessed with this last night and figured a few things out. Firstly I reverted back to 3.1.1 on this github. It created a secondary problem which I fixed as well. I'm not sure if this is stable in the long term but currently I haven't run into any problems.

Instructions: 
Install Una via the install.sh script or via makedeb una-bin
Download the 3.1.1 repo
overwrite bin/bash una & una-updater w/ the 3.1.1's version

This will remove the whole creating directory stuff but will cause a new issue where you can't install because it won't find PKGBuild when using "Una Install *Package*"

To fix this I went into una's bin and deleted all ".git". Note do not remove -git just .git. It'll fix the install problem and everything will work as intended.

**Comment by deadmantfa** [comment]
I will try this out

**Comment by RudraSwat** [comment]
This issue should be fixed now (I've updated the install script).

**Comment by jonas-w** [comment]
Mhm the same problem, now that i've removed the .git. The same neverending "creating una directory and config files"

**Comment by deadmantfa** [comment]
![image](https://user-images.githubusercontent.com/1812611/171593811-9467dafb-5316-47f1-bbb5-7994bc491d76.png)

The issue still persists installation fails

**Comment by roworu** [comment]
Same here..
![image](https://user-images.githubusercontent.com/36964755/171798973-3a062eec-c619-42bf-b3eb-5603aad97a74.png)
